### ISSUE TITLE
java.util.NoSuchElementException: None.get

### ISSUE THREAD

**Issue by Hubbitus** [stoerr/GrokConstructor#6] opened 2015-07-02 13:21 UTC
It seams all present on your erro page:

```
OUCH!

I'm sorry, but you have encountered a bug or missing nice display of an error message in the application. If you can't guess the problem from the error message, please contact Hans-Peter Störr (www.stoerr.net yu4cheem@techno.ms) with a copy of this page, or open an issue on https://github.com/stoerr/GrokConstructor/issues .

Please remember that you can always press the back button to fix what was wrong - there is no state on the server, only in the page shown in the browser.



Error message: java.util.NoSuchElementException: None.get


Request Info:
http://grokconstructor.appspot.com/do/constructionstep?null:
{"grokadditional":[""],"submit":["Continue!"],"pattern":["\\A%{TIMESTAMP_ISO8601} \\[%{USERNAME}] \\[%{UUID}] \\[%{USERNAME}] %{LOGLEVEL} %{JAVACLASS}:%{INT} - %{INT} ms; \\[%{DATA}];\\[%{USERNAME}"],"multiline":[""],"nameOfNextPart":[""],"loglines":["2015-06-30 03:09:19,190 [catalina-backend-exec-51] [762f2bed-3ac9-4e43-8516-643c42f39491] [forestry_00402_001] DEBUG ru.rlh.egais.portal.backend.jdbc.SQL.logSql:188 - 0 ms; [SELECT count(*)  FROM bo_forestry forestry  INNER JOIN bo_constituent_entity c  onstituent_entity ON constituent_entity.id = forestry.bo_const_entity_fkey  WHERE forestry.id = ? and constituent_entity.id =   ?];[G_00402,27]"],"nextPartPerHand":["]"],"groklibs":["java","grok-patterns"],"nextPart":["ksdf8wej2349j_ThisIsAMarkerForNextPartThatNextPartPerHandWasChoosen"]}


java.util.NoSuchElementException: None.get
    at scala.None$.get(Option.scala:344)
    at scala.None$.get(Option.scala:342)
    at net.stoerr.grokconstructor.incremental.IncrementalConstructionStepView$$anonfun$2.apply(IncrementalConstructionStepView.scala:26)
    at net.stoerr.grokconstructor.incremental.IncrementalConstructionStepView$$anonfun$2.apply(IncrementalConstructionStepView.scala:24)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
    at scala.collection.AbstractTraversable.map(Traversable.scala:104)
    at net.stoerr.grokconstructor.incremental.IncrementalConstructionStepView.(IncrementalConstructionStepView.scala:23)
    at net.stoerr.grokconstructor.webframework.WebDispatcher.giveView(WebDispatcher.scala:58)
    at net.stoerr.grokconstructor.webframework.WebDispatcher.doGet(WebDispatcher.scala:32)
    at net.stoerr.grokconstructor.webframework.WebDispatcher.doPost(WebDispatcher.scala:26)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
    at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:35)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:257)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
    at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:76)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:146)
    at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:482)
    at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:437)
    at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:444)
    at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:230)
    at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:308)
    at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:300)
    at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:441)
    at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:234)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by stoerr** [comment] 2016-10-03 13:07
The problem is that the given next part per hand doesn't match, and this doesn't  create a sensible error message.

**Comment by stoerr** [comment] 2016-10-03 13:29
Actually, this is a duplicate of #3 . So I'm closing this.

**Closed as completed by stoerr** 2016-10-03 13:29 UTC
