### ISSUE TITLE
tab instead of space on grok definition breaks-down the page

### ISSUE THREAD

**Issue by J-SbiN** [stoerr/GrokConstructor#30] opened 2017-08-21 15:41 UTC
Hi!
The grock contructor is agreat tool! I've been using it for the last month to check my groks.
For a few times I copied groks and the page broke down when I clicked 'Go!' - I'v just understood why:

Every time you copy a "<GROKNAME> <regex>" into the new grok expression and the delimiter between the grok name field and the regex field is not a space (if it is a tab, for example), when you click 'Go!' the entire page breaks down and loses all information.

This would be nice to fix! but I do not have the skills for it.
Thanks

**Comment by stoerr** [comment] 2017-08-28 07:29
Thanks for the report! Sorry, I could not reproduce the bug and don't quite understand what you are doing. Could you please include either a screenshot if the normal page layout is shown, or, if it's the "OUCH!" bug page, just paste the contents of that page into a comment?

**Comment by stoerr** [comment] 2022-06-18 18:56
I'm closing this since there was no answer.

**Closed as completed by stoerr** 2022-06-18 18:56 UTC
