### ISSUE TITLE
Got an error while using the website, it asked to file a bug report  

### ISSUE THREAD

**Issue by cschnei3** [stoerr/GrokConstructor#19] opened 2016-08-26 13:15 UTC
![screen shot 2016-08-26 at 3 13 45 pm](https://cloud.githubusercontent.com/assets/6611562/18006445/d39ab14c-6b9f-11e6-921a-415243398225.png)

**Comment by stoerr** [comment] 2016-10-03 13:28
Unfortunately It'd be quite complicated to present the error message in the normal page, here. But I thought the error message explains the problem quite clearly, doesn't it? If not, please protest. 

I'm prepared to change the error message, but not that this is presented in the "Oops" page. So I'm closing this for now.

**Comment by stoerr** [comment] 2016-10-03 13:29
Ah, actually this is a duplicate of #4 .

**Closed as completed by stoerr** 2016-10-03 13:28 UTC
